#!/bin/bash
#set -e
###############################################################################
# Author	:	DarkXero
# Website	:	https://www.xerolinux.online
###############################################################################

echo "###############################################################################"
echo "###                               Check 1  LSPCI                           ####"
echo "###############################################################################"
echo

lspci -vnnn | perl -lne 'print if /^\d+\:.+(\[\S+\:\S+\])/' | grep VGA

echo
echo "###############################################################################"
echo "###                               Check 2  GLXINFO                         ####"
echo "###############################################################################"
echo

if test -f /usr/bin/glxinfo ; then
	echo "glxinfo is present"
	echo
else
	echo "We have installed glxinfo to get more info on your graphical card"
	echo "info  : mesa-demos provides the same glxinfo tool - it will conflict with this package"
	sudo pacman -S glxinfo --noconfirm
fi

glxinfo|egrep "OpenGL vendor|OpenGL renderer*"

echo
echo "###############################################################################"
echo "###                               Check 3  NVIDIA-SMI                      ####"
echo "###############################################################################"
echo

if pacman -Qi nvidia-utils &> /dev/null; then
	nvidia-smi -L
else
	echo "No nvidia driver present"
fi

echo "###############################################################################"
echo "###                               DONE                                     ####"
echo "###############################################################################"
